In [1]:
# data processing
import pandas as pd
import imblearn
from pylab import *
%matplotlib inline
import pickle as pkl
import os
import rasterio as rio

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

from warnings import simplefilter
# ignore all future warnings
simplefilter(action='ignore', category=UserWarning)
from training import *

# Load data

In [2]:
data_dir = 'C:/Users/MABEB16/science/postdoc/5_projects/1_general_classifier/4_general_classifier/results/1_features/'
df = pd.read_csv(data_dir+'dataset_file_transformed.csv')
sites = df['site'].unique()

non_predictive_columns = ['x_pos', 'y_pos', 'site', 'class_certainty', 'veg_class']

# Train in-site model and save classifier as pickle object

In [3]:
save_dir = 'C:/Users/MABEB16/science/postdoc/5_projects/1_general_classifier/4_general_classifier/results/2a_classifier/RF_is/'

feat_importance_dict = {}
cf_matrix_dict = {}
accuracies = []

#sites = ['CG1-8A', 'CG1-8B', 'CS-103A', 'CS-103B', 'CS-46A', 'CS-46B', 'CS-59B', 'CS-96B', 'CS117B', 'CS3A', 'CS3B', 'CS3C', 'F3-19B', 'F3-19C', 'F3-20A', 'F3-20B',
#         'F3-20C', 'F3-8A', 'F3-8B', 'F3-8C', 'SS33-1C', 'SS33-4A', 'SS33-9A', 'ZF20-11A', 'ZF20-35A', 'ZF20-4A', 'ZF20-59B', 'ZF20-6B', 'ZF20-8B', 'ZF20-9A', 
#         'ZF20-9C', 'ZF46-15A', 'ZF46-18B', 'ZF46-21B', 'ZF46-37A', 'ZF46-45A']

#sites = ['CG1-8A', 'CG1-8B', 'CS-103A', 'CS-103B', 'CS-46A', 'CS-46B', 'CS-59B', 'CS-96B', 'CS117B', 'CS3A', 'CS3B', 'F3-19B', 'F3-19C', 'F3-20A', 'F3-20B',
#         'F3-20C', 'F3-8A', 'F3-8B', 'F3-8C', 'SS33-1C', 'SS33-4A', 'SS33-9A', 'ZF20-11A', 'ZF20-35A', 'ZF20-4A', 'ZF20-59B', 'ZF20-6B', 'ZF20-8B', 'ZF20-9A', 
#         'ZF20-9C', 'ZF46-15A', 'ZF46-18B', 'ZF46-21B', 'ZF46-37A', 'ZF46-45A']

#sites = ['CS3C']
df_w = certainty_weight(df)

for site in sites:
    model, extra_metrics, _ = in_site_RF(df, site, extra_metrics=True, non_predictive_columns=non_predictive_columns)
    with open(save_dir+f'RF_{site}.pkl', 'wb') as file: 

        # A new file will be created 
        pkl.dump(model, file)
    
    # extra metrics
    feat_importance_dict[site] = extra_metrics['feature_importance']
    
    cf_matrix_dict[site] = extra_metrics['cf_matrix']
    
    train_acc = str(extra_metrics['train_accuracy'])
    test_acc = str(extra_metrics['test_accuracy'])
    accuracies.append(f'{site}, {train_acc}, {test_acc}')
    

# -----------------------------------------------------------------------------------------------------------------------------------------------------------------------
# saving model performance metrics (confusion matrix (cf), permutation importance, accuracies)
save_dir = 'C:/Users/MABEB16/science/postdoc/5_projects/1_general_classifier/4_general_classifier/results/2b_classifier_performance/RF_is/'

with open(save_dir+f'RFis_cf_matrix.pkl', 'wb') as file:
    pkl.dump(cf_matrix_dict, file)
    
with open(save_dir+f'RFis_feat_importance.pkl', 'wb') as file:
        pkl.dump(feat_importance_dict, file)
        
with open(save_dir+'RFis_accuracies.txt', 'w') as outfile:
    outfile.write('site, train_acc, test_acc\n')
    outfile.write('\n'.join(str(i) for i in accuracies))
outfile.close()

Processing CG1-8A...
Processing CG1-8B...
Processing CS-103A...
Processing CS-103B...
Processing CS-46A...
Processing CS-46B...
Processing CS-59B...
Processing CS-96B...
Processing CS117B...
Processing CS3A...
Processing CS3B...
Processing CS3C...
Processing F3-19B...
Processing F3-19C...
Processing F3-20A...
Processing F3-20B...
Processing F3-20C...
Processing F3-8A...
Processing F3-8B...
Processing F3-8C...
Processing SS33-1C...
Processing SS33-4A...
Processing SS33-9A...
Processing ZF20-11A...
Processing ZF20-35A...
Processing ZF20-4A...
Processing ZF20-59B...
Processing ZF20-6B...
Processing ZF20-8B...
Processing ZF20-9A...
Processing ZF20-9C...
Processing ZF46-15A...
Processing ZF46-18B...
Processing ZF46-21B...
Processing ZF46-37A...
Processing ZF46-45A...

In [133]:
df_site = df_w[df_w['site'] == site]
c = Counter(df_site['veg_class'])
class_leastcommon = c.most_common()[:-2:-1][0][0]
class_leastcommon
df_class = df_site[df_site['veg_class'] == class_leastcommon]
df_class

       site  y_pos  x_pos  veg_class  ...         Y          L  z_score_Y  z_score_L
40702  CS3C   5003   1856          9  ...  0.088807  35.753541  -1.176045  -1.377991
40703  CS3C   5003   1857          9  ...  0.082438  34.485457  -1.212514  -1.457070
40704  CS3C   5004   1856          9  ...  0.097733  37.432536  -1.124933  -1.273287
40705  CS3C   5004   1857          9  ...  0.088807  35.753541  -1.176045  -1.377991
63509  CS3C   5003   1856          9  ...  0.088807  35.753541  -1.176045  -1.377991
63510  CS3C   5003   1857          9  ...  0.082438  34.485457  -1.212514  -1.457070
63511  CS3C   5004   1856          9  ...  0.097733  37.432536  -1.124933  -1.273287
63512  CS3C   5004   1857          9  ...  0.088807  35.753541  -1.176045  -1.377991
86316  CS3C   5003   1856          9  ...  0.088807  35.753541  -1.176045  -1.377991
86317  CS3C   5003   1857          9  ...  0.082438  34.485457  -1.212514  -1.457070
86318  CS3C   5004   1856          9  ...  0.097733  37.432536  -1.124933  -1.273287
86319  CS3C   5004   1857          9  ...  0.088807  35.753541  -1.176045  -1.377991

[12 rows x 25 columns]

In [83]:
a = [1, 3, 5, 6, 9, 10, 14, 15, 56]
np.where(a == 10)

(array([], dtype=int64),)

In [28]:
sites = ['F3-20C']
for site in sites:
    df_site = df_w[df_w['site'] == site]
df_site

          site  y_pos  x_pos  ...          L  z_score_Y  z_score_L
3916    F3-20C   1016   4889  ...  98.774812   1.777897   1.407332
3917    F3-20C   1016   4890  ...  99.142528   1.812381   1.426140
3918    F3-20C   1017   4889  ...  97.854086   1.692516   1.360241
3919    F3-20C   1017   4890  ...  99.333367   1.830365   1.435900
3920    F3-20C   1104   4601  ...  51.906111  -1.057810  -0.989816
...        ...    ...    ...  ...        ...        ...        ...
115125  F3-20C   9278   1831  ...  25.046077  -1.634915  -2.363601
120157  F3-20C   4267    895  ...  72.467926  -0.160685   0.061839
120158  F3-20C   4267    896  ...  71.502810  -0.213704   0.012477
120159  F3-20C   4268    895  ...  71.703573  -0.202771   0.022746
120160  F3-20C   4268    896  ...  73.320842  -0.112857   0.105463

[3520 rows x 25 columns]

In [38]:
from collections import Counter

site = 'F3-20A'
#check_samples = df['site'].isin([site])
check_samples = df[df['site'] == site]
c = min(Counter(check_samples['veg_class']).values())
print(c)

4

In [14]:
df[df['site'] == site]

         site  y_pos  x_pos  ...          L  z_score_Y  z_score_L
16264  F3-20A    499   6344  ...  79.295489   0.832539   0.882473
16265  F3-20A    499   6345  ...  83.338619   1.131354   1.067510
16266  F3-20A    500   6344  ...  87.209399   1.441161   1.244659
16267  F3-20A    500   6345  ...  84.667667   1.235064   1.128335
16268  F3-20A    585   8527  ...  74.407706   0.503661   0.658780
...       ...    ...    ...  ...        ...        ...        ...
17426  F3-20A  14803   2549  ...  68.179521   0.133189   0.373742
17427  F3-20A  14989   3331  ...  57.755548  -0.374742  -0.103319
17428  F3-20A  14989   3332  ...  62.027094  -0.182730   0.092172
17429  F3-20A  14990   3331  ...  62.891170  -0.141226   0.131717
17430  F3-20A  14990   3332  ...  59.097925  -0.316720  -0.041884

[1167 rows x 25 columns]

# Functions - code development
TODO: Outsource to aux file

In [ ]:
def certainty_weight(df):
    cert1_indices = df['class_certainty'].isin([1])
    cert2_indices = df['class_certainty'].isin([2])
    cert3_indices = df['class_certainty'].isin([3])
    cert4_indices = df['class_certainty'].isin([4])

    df_cert1 = pd.concat([df[cert1_indices].reset_index(drop=True)]*4, ignore_index=True)
    df_cert2 = pd.concat([df[cert2_indices].reset_index(drop=True)]*3, ignore_index=True)
    df_cert3 = pd.concat([df[cert3_indices].reset_index(drop=True)]*2, ignore_index=True)
    df_cert4 = pd.concat([df[cert4_indices].reset_index(drop=True)]*1, ignore_index=True)

    df_weighted = pd.concat([df_cert1, df_cert2, df_cert3, df_cert4], ignore_index=True)
    
    return df_weighted

In [2]:
def split_xy(df):
    feature_columns = [c for c in list(df.columns) if c not in non_predictive_columns]
    X = df[feature_columns]
    y = df['veg_class']
    return X, y


# Used for single site classifiers
def site_specific_RF(data, site, test_size=0.33, extra_metrics=False):
    print(f'Processing {site}...')
    df_site = df[df['site'] == site]
    df_reduced = df_site[df_site['class_certainty'] <= 2]
    X, y = split_xy(df_site)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

    # -------------------------------
    # oversample w synthetic minority oversampling to balance classes
    under = imblearn.over_sampling.SMOTE(sampling_strategy='not majority') # resamples all classes but majority
    X_res, y_res = under.fit_resample(X_train, y_train)

    # -----------------------------------------------------------------------------------------------------------
    # Train RF classifier
    clf=RandomForestClassifier(n_estimators=600, max_depth=6, n_jobs=12)
    clf.fit(X_res.values, y_res.values)

    # -----------------------------------------------------------------------------------------------------------
    # Prediction
    preds = clf.predict(X_test.values)

    #print(f'  Train accuracy: {clf.score(X_res, y_res)}')
    #print(f'  Test accuracy: {clf.score(X_test, y_test)}')

    if extra_metrics:
        # -----------------------------------------------------------------------------------------------------------
        # Inspect performance parameters: training and testing scores, confusion matrix, and feature importanceax1 = plt.figure(figsize=(5,5)).add_subplot(111)
        extra_metrics = {}

        extra_metrics['cf_matrix'] = confusion_matrix(y_test, preds,  labels = clf.classes_)
        #disp = ConfusionMatrixDisplay(confusion_matrix=cf_matrix, display_labels=clf.classes_)
        #disp.plot()
        #plt.title('Confusion Matrix')

        extra_metrics['feature_importance'] = pd.DataFrame(clf.feature_importances_, index=X_res.columns).sort_values(by=0, ascending=False)
        #print(feature_importance)
        
        extra_metrics['train_accuracy'] = clf.score(X_res, y_res)
        extra_metrics['test_accuracy'] = clf.score(X_test, y_test)
        
        return clf, extra_metrics, preds
    
    else:
        return clf, preds

In [52]:
#with open(data_dir+'cf_matrix.pkl', 'rb') as file:      
#    cf_matrix = pkl.load(file) 
#print(cf_matrix['CG1-8A'])

In [ ]:
model_dir = 'C:/Users/MABEB16/science/postdoc/5_projects/1_general_classifier/4_general_classifier/RF_classifers/'
with open(model_dir+'RF_CS-103A.pkl', 'rb') as file:      
    model = pkl.load(file) 
#print(cf_matrix['CG1-8A'])

# Classify site

In [53]:
site = 'CS-103A'
run_name = f'{site}_01'

# location of raw lichen data
data_dir = 'C:/Users/MABEB16/science/postdoc/5_projects/1_general_classifier/2_labelling/hp'

# place where we stored chunked feature data
run_dir = f'C:/Users/MABEB16/science/postdoc/5_projects/1_general_classifier/4_general_classifier/runs/{run_name}'

Processing block 0-0
Processing block 0-1
Processing block 0-2
Processing block 0-3
Processing block 1-0
Processing block 1-1
Processing block 1-2
Processing block 1-3
Processing block 2-0
Processing block 2-1
Processing block 2-2
Processing block 2-3
Processing block 3-0
Processing block 3-1
Processing block 3-2
Processing block 3-3

In [60]:
#out_file = '/network/scratch/m/matthew.fortier/CS-103A-classified.tif'
out_file = 'C:/Users/MABEB16/science/postdoc/5_projects/1_general_classifier/4_general_classifier/runs/CS-103A-classified.tif'

meta.update(count=1)

# Write a new .tif file using the metadata from the original file
with rio.open(out_file, 'w', **meta) as dst:
    dst.write(output, 1)